INSERT INTO hierarchy (jobhierarchyid, division, department, job, par_level)
	VALUES ( 1, 'Food and Beverage', 'Banquets', 'Banquet Captain', 2),
		(2, 'Food and Beverage', 'Banquets', 'Banquet Chef', 3),
        (3, 'Food and Beverage', 'Banquets', 'Banquet Manager', 2),
        (4, 'Food and Beverage', 'Banquets', 'Banquets Sous Chef', 3),
        (5, 'Food and Beverage', 'Banquets', 'Bartender - Banquets', 1),
        (6, 'Food and Beverage', 'Banquets', 'Cook - Banquets', 2),
        (7, 'Food and Beverage', 'Banquets', 'Coordinator - Sales/Catering', 1),
        (8, 'Food and Beverage', 'Banquets', 'Open Air Help', 1),
        (9, 'Food and Beverage', 'Banquets', 'Sales/Banquets Manager', 1),
        (10, 'Food and Beverage', 'Banquets', 'Server - Banquets', 2),
        (11, 'Food and Beverage', 'Banquets', 'Set up - Banquets', 1),
        (12, 'Food and Beverage', 'Beverage', 'Asst Beverage Manager/Lead Bartender', 2),
        (13, 'Food and Beverage', 'Beverage', 'Beverage Manager', '1'),
        (14, 'Food and Beverage', 'Beverage', 'Beverage Supervisor', 1);
	
INSERT INTO hierarchy (jobhierarchyid, division, department, job, par_level)
	VALUES (15, 'Food and Beverage', 'Casino Services Bar', 'Cash Server - Casino Services Bar', '2'),
		(16, 'Food and Beverage', 'Center Bar','Bartender - Center Bar', '2'),
        (17, 'Food and Beverage', 'Center Bar', 'Cash Server - Center Bar', '2'),
        (18, 'Food and Beverage', 'Center Bar', 'Porter - Center Bar', '1'),
        (19, 'Food and Beverage', 'Firebreak', 'Assistant Manager - Firebreak', '2'),
        (20, 'Food and Beverage', 'Firebreak', 'Barback - Firebreak', '3'),
        (21, 'Food and Beverage', 'Firebreak', 'Bartender - Firebreak', '2'),
        (22, 'Food and Beverage', 'Firebreak', 'Busser - Firebreak', '2'),
        (23, 'Food and Beverage', 'Firebreak', 'Chef - Firebreak', '2'),
        (24, 'Food and Beverage', 'Firebreak', 'Cook - Firebreak', '2'),
        (25, 'Food and Beverage', 'Firebreak', 'Food Runner - Firebreak', '2'),
        (26, 'Food and Beverage', 'Firebreak', 'General Manager - Firebreak', '2'),
        (27, 'Food and Beverage', 'Firebreak', 'Host - Firebreak', '1'),
        (28, 'Food and Beverage', 'Firebreak', 'Lead Cook - Firebreak', '2'),
        (29, 'Food and Beverage', 'Firebreak', 'Prep Cook- Firebreak', '2'),
        (30, 'Food and Beverage', 'Firebreak', 'Resturant Supervisor - Firebreak', '2'),
        (31, 'Food and Beverage', 'Firebreak', 'Server - Firebreak', '2'),
        (32, 'Food and Beverage', 'Firebreak', 'Sous Chef - Firebreak', '2'),
        (33, 'Food and Beverage', 'Fuel', 'Barista - Fuel Cafe', '2'),
        (34, 'Food and Beverage', 'Fuel', 'Supervisor - Fuel Cafe', '2'),
        (35, 'Food and Beverage', 'North Bar', 'Bartender - North Bar', '2'),
        (36, 'Food and Beverage', 'North Bar', 'Cash Server - North Bar', '2'),
        (37, 'Food and Beverage', 'North Bar', 'Porter - North Bar', '2'),
        (38, 'Food and Beverage', 'Oyster Bar', 'Busser - Oyster Bar', '2'),
        (39, 'Food and Beverage', 'Oyster Bar', 'Cook - Oyster Bar', '3'),
        (40, 'Food and Beverage', 'Oyster Bar', 'Host - Oyster Bar', '1'),
        (41, 'Food and Beverage', 'Oyster Bar', 'Server - Oyster Bar', '2'),
        (42, 'Food and Beverage', 'Oyster Bar', 'Sous Chef - Oyster Bar', '3'),
        (43, 'Food and Beverage', 'Park Prime', 'Assistant Manager - Steakhouse', '2'),
        (44, 'Food and Beverage', 'Park Prime', 'Bartender - Steakhouse', '2'),
        (45, 'Food and Beverage', 'Park Prime', 'Busser - Steakhouse', '2'),
        (46, 'Food and Beverage', 'Park Prime', 'Cook - Steakhouse', '3'),
        (47, 'Food and Beverage', 'Park Prime', 'Chef - Steakhouse', '3'),
        (48, 'Food and Beverage', 'Park Prime', 'General Manager - Steakhouse', '2'),
        (49, 'Food and Beverage', 'Park Prime', 'Host - Steakhouse', '1'),
        (50, 'Food and Beverage', 'Park Prime', 'Server - Steakhouse', '2'),
        (51, 'Food and Beverage', 'Pool Bar', 'Bartender - Pool Bar', '2'),
        (52, 'Food and Beverage', 'Pool Bar', 'Cabana Attendant - Pool Bar', '1'),
        (53, 'Food and Beverage', 'Pool Bar', 'Cash Server - Pool Bar', '2'),
        (54, 'Food and Beverage', 'Pool Bar', 'Lifegaurd - Pool Bar', '2'),
        (55, 'Food and Beverage', 'Pool Bar', 'Lifegaurd Instructor', '1'),
        (56, 'Food and Beverage', 'Pool Bar', 'Pool Supervisor - Pool Bar', '2'),
        (57, 'Food and Beverage', 'Pool Bar', 'Porter - Pool Bar', '1'),
        (58, 'Food and Beverage', 'Room Service', 'Line Cook - Room Service', '2'),
        (59, 'Food and Beverage', 'Room Service', 'Server - Room Service', '2'),
        (60, 'Food and Beverage', 'Room Service', 'Supervisor - Room Service', '2');
        
 

INSERT INTO hierarchy (jobhierarchyid, division, department, job, par_level)
	VALUES (61, 'Finance', 'Cage', 'Dual Rate Supervisor', '2'),
        (62, 'Finance', 'Cage', 'Employee Banker', '2'),
        (63, 'Finance', 'Cage', 'Main Banker - Vault Staff', '2'),
        (64, 'Finance', 'Cage',  'Player Services - Cage Manager', '2'),
        (65, 'Finance', 'Cage', 'Player Services - Cage Rep', '2'),
        (66, 'Finance', 'Cage', 'Player Services - Cage Supervisor', '2'),
        (67, 'Finance', 'Count', 'Count Room Staff', '2'),
        (68, 'Finance', 'Count', 'Count Room Supervisor', '2');


INSERT INTO hierarchy (jobhierarchyid, division, department, job, par_level)
	VALUES (69, 'Facilities', 'Engineering', 'Director/Chef Engineer - Facilities', '3'),
		(70, 'Facilities', 'Engineering', 'Engineer - Facilities', '3'),
        (71, 'Facilities', 'Engineering', 'Groundskeeper - Facilities', '3'),
        (72, 'Facilities', 'Engineering', 'Lead Boiler Tech - Facilities', '3'),
        (73, 'Facilities', 'Engineering', 'Lead Electrician - Facilities', '3'),
        (74, 'Facilities', 'Engineering', 'Lead Groundskeeper - Facilities', '3'),
        (75, 'Facilities', 'Engineering', 'Lead PM Engineer - Facilities', '3'),
        (76, 'Facilities', 'Engineering', 'Maintenance Supervisor - Facilities', '3'),
        (77, 'Facilities', 'Engineering', 'Service Writer - Facilities', '3');
        
        
INSERT INTO hierarchy (jobhierarchyid, division, department, job, par_level)
	VALUES (78, 'Hotel', 'Front Desk', 'Concierge', '2'),
		(79, 'Hotel', 'Front Desk', 'Director Of Hotel Operations', '2'),
        (80, 'Hotel', 'Front Desk', 'Front Desk - Night Audit', '2'),
        (81, 'Hotel', 'Front Desk', 'Front Desk - Agent', '2'),
        (82, 'Hotel', 'Front Desk', 'Manager Of Hotel Operations', '2'),
        (83, 'Hotel', 'Front Desk', 'Projects', '2'),
        (84, 'Hotel', 'Front Desk', 'Reservations Agent', '2'),
        (85, 'Hotel', 'Front Desk', 'Reservations Supervisor', '2'),
        (86, 'Hotel', 'Front Desk', 'Supervisor Of Hotel Operations', '2'),
        (87, 'Hotel', 'Gift Shop', 'Cashier - Gift Shop', '2'),
        (88, 'Hotel', 'Gift Shop', 'Cashier - Sundries', '2'),
        (89, 'Hotel', 'Gift Shop', 'Supervisor - Gift Shop', '2'),
        (90, 'Hotel', 'Valet', 'Front Services Attendant', '2'),
        (91, 'Hotel', 'Valet', 'Front Services Lead Attendant', '2'),
        (92, 'Housekeeping', 'Housekeeping', 'Housekeeping Attendant', '2'),
        (93, 'Housekeeping', 'Laundry', 'Attendant - Laundry/Uniforms', '2'),
        (94, 'Housekeeping', 'Laundry', 'Lead - Laundry/Uniforms', '2'),
        (95, 'Purchasing', 'Warehouse', 'Lead Warehouse Reciever', '2'),
        (96, 'Purchasing', 'Warehouse', 'Receiving Clerk - Warehouse', '2'),
        (97, 'Purchasing', 'Warehouse', 'Laborer', '2'),
        (98, 'Security', 'Security', 'Director - Security/Surveillance', '2'),
        (99, 'Security', 'Security', 'Lead Security Officer', '2'),
        (100, 'Security', 'Security', 'Officer - Security', '2'),
        (101, 'Security', 'Security', 'Supervisor - Security', '2'),
        (102, 'Security', 'Surveillance', 'Surveillance Agent', '2'),
        (103, 'Security', 'Surveillance', 'Surveillance Supervisor', '2'),
        (104, 'Security', 'Surveillance', 'Surveillance Technician', '2'),
        (105, 'Casino Operations', 'Slots', 'Slot Floor Attendants', '2'),
        (106, 'Casino Operations', 'Slots', 'Slot Floor Supervisors', '2'),
        (107, 'Casino Operations', 'Slots', 'Slot Manager', '2'),
        (108, 'Casino Operations', 'Slots', 'Slot Shift Manager', '2'),
        (109, 'Casino Operations', 'Slots', 'Slot Tech Apprentice', '2'),
        (110, 'Casino Operations', 'Slots', 'Slot Tech Supervisor', '2'),
        (111, 'Casino Operations', 'Slots', 'Slot Techs', '2'),
        (112, 'Casino Operations', 'Table Games', 'Assistant Shift Manager', '2'),
        (113, 'Casino Operations', 'Table Games', 'Casino Shift Manager', '2'),
        (114, 'Casino Operations', 'Table Games', 'Duel Rate Supervisor', '2'),
        (115, 'Casino Operations', 'Table Games', 'Gaming Director', '2'),
        (116, 'Casino Operations', 'Table Games', 'Table Games Dealer III - All Games', '2'),
        (117, 'Casino Operations', 'Table Games', 'Table Games Manager', '2'),
        (118, 'Casino Operations', 'Table Games', 'Table Games Assistant', '2');